nursingace/contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Start business urls
    path('', views.contact_form_view, name='contactform'),
    path('subscribe/', views.subscribe, name='subscribe'),
    # path('subs/', views.subs, name='subs'),
]

nursingace/nursingace/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from search import views as search_views
from wagtail.contrib.sitemaps.views import sitemap

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('products/', include('products.urls')),
    path('contact/', include('contact.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', search_views.search, name='search'),   
    path('sitemap.xml', sitemap)
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    import debug_toolbar
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
   
   

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

nursingace/contact/models.py
from pyexpat import model
from django.db import models

# Create your models here.

class Subscriber(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(max_length=100) 
    active = models.BooleanField(default=True)   

    def __str__(self):
        return self.email

class ModelContact(models.Model):   
    date_added = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    e_mail = models.EmailField(max_length=100)    
    phone_number = models.CharField(max_length=13, blank=True, null=True)
    business = models.CharField(max_length=100)
    message = models.TextField()


    def __str__(self):
        return f'{self.first_name} {self.first_name}'
    @property
    def full_name(self):
        return f'{self.first_name} {self.first_name}'

nursingace/home/models.py
from django.db import models
from wagtail.core.fields import StreamField
from wagtail.core.models import Page
from wagtail.core import blocks
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtailmetadata.models import MetadataPageMixin
from wagtail.admin.edit_handlers import FieldPanel, PageChooserPanel, StreamFieldPanel, MultiFieldPanel
from streams import nca_blocks
import requests
class HomePage(MetadataPageMixin, Page):
    max_count = 1
    
    templates = 'home/home_page.html'
    subpage_types = ['otherpages.AboutPage', 'resources.ArticlesListPage', 'otherpages.PolicyPage',]
    banner_title = models.CharField(max_length=43)
    banner_description = models.TextField()
    
    
    banner_cta = models.ForeignKey(
        'wagtailcore.page',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'        
        )

    # section about
  
    section_about = StreamField([
        ('About_section', nca_blocks.EyebrowHeaderDescription(null=True))
    ],null=True, max_num=1)


    jumbo_area = StreamField([
        ('jumbo_cards', nca_blocks.JumboBlock(null=True))
    ],null=True, max_num=1)

    about_bullet = StreamField([
        ('about_bullet', blocks.CharBlock(required=False)),       
    ], null=True)

    section_about_content = StreamField([
         ('description', blocks.RichTextBlock(required=False, help_text='Section description'))        
        
    ], null=True, max_num=1)

    section_about_image= models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        related_name='+'
    )

 # section about
    core_features = StreamField([
        ('section_core_section', nca_blocks.EyebrowHeaderDescription()),
     
    ],null=True, max_num=1)

    core_features_cards = StreamField([        
        ('features_cards', nca_blocks.CardBlock())
    ],null=True, max_num=3)

# Citation Hub
    citation_hub = StreamField([
        ('citation_section', nca_blocks.EyebrowHeaderDescription()),        
    ],null=True, max_num=1)
    citation_styles = StreamField([
        ('citationStyle', nca_blocks.RichTextAndImage()),        
    ],null=True)
# timely updates
    timely_updates = StreamField([
        ('timely_updates', nca_blocks.EyebrowHeaderDescription()),        
    ],null=True, max_num=1)
    timely_updates_bullet = StreamField([
        ('updates_bullet', blocks.CharBlock(required=False)),       
    ], null=True)

# datasection
    datasection = StreamField([
        ('datasection_headings', nca_blocks.EyebrowHeaderDescription()),        
    ],null=True, max_num=1)
    data_card = StreamField([
        ('data_counter', nca_blocks.DataCardBlock()),        
    ],null=True)
  
    data_bullets = StreamField([
        ('data_bullets', blocks.CharBlock(required=False)),       
    ], null=True)



    content_panels = Page.content_panels + [
        FieldPanel('banner_title'),
        FieldPanel('banner_description'),
        PageChooserPanel('banner_cta'),   

        StreamFieldPanel('jumbo_area'),    

        MultiFieldPanel(
        [ StreamFieldPanel('section_about'),
        StreamFieldPanel('about_bullet'),
        StreamFieldPanel('section_about_content'),
        ImageChooserPanel('section_about_image'),        
        ],
        heading="About Section",
        classname=""
        ),

        MultiFieldPanel(
        [
        
        StreamFieldPanel('core_features'),
        StreamFieldPanel('core_features_cards'),
        ],
        heading="Core Features Section",
        classname=""
        ),
        
        MultiFieldPanel(
        [
        StreamFieldPanel('citation_hub'),
        StreamFieldPanel('citation_styles'),

        ],
        heading="Citation Section",
        classname=""
        ),

        MultiFieldPanel(
        [
        StreamFieldPanel('timely_updates'),
        StreamFieldPanel('timely_updates_bullet'),

        ],
        heading="Timely CTA Updates Section",
        classname=""
        ),
        MultiFieldPanel(
        [
        StreamFieldPanel('datasection'),
        StreamFieldPanel('data_card'),
        StreamFieldPanel('data_bullets'),

        ],
        heading="Data Section",
        classname=""
        ),  
    ]



    def get_context(self, request, *args, **kwargs):

        context = super().get_context(request, *args, **kwargs)
        try:
            managementUrl = 'https://appnursing.cannyva.com/assignments/getprice/'  
            pricingData = requests.get(managementUrl).json()
        
        except:
            pricingData ={}
    
        context['study_level'] = pricingData.get('study_level')
        context['service_category'] = pricingData.get('service_category')
        context['assignment_type'] = pricingData.get('assignment_type')
        context['turnaround'] = pricingData.get('turnaround')
   

        return context

nursingace/nursingace/templates/home/contact-us.html
{% extends "base.html" %}
{% load static %}
 {% block content %}


      <main>

         <!-- page title area start -->
         <section class="page__title-area page__title-height d-flex align-items-center fix p-relative z-index-1" data-background="{% static 'images/page-title/page-title.jpg' %}">
   
            <div class="container">
               <div class="row">
                  <div class="col-xxl-12">
                     <div class="page__title-wrapper text-center">
                        <h3>Contact </h3>
                           <nav aria-label="breadcrumb">
                              <ol class="breadcrumb justify-content-center">
                                 <li class="breadcrumb-item"><a href="/">Home</a></li>
                                 <li class="breadcrumb-item active" aria-current="page">Contact</li>
                              </ol>
                           </nav>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!-- page title area end -->

          <!-- contact area start  -->
        
          <section class="contact__area pb-150 p-relative z-index-1">
             <div class="container">
                <div class="row">
                   <div class="col-xxl-12 col-xl-12 col-lg-12">
                      <div class="contact__wrapper white-bg mt--70 p-relative z-index-1 wow fadeInUp" data-wow-delay=".3s">
                         <div class="row">
                          
                           {% if messages %}
                           <ul class="messages">
                               {% for message in messages %}
                               <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                 <strong>{{ message }}</strong> 
                                 <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                               </div>
                      
                               {% endfor %}
                           </ul>
                           {% endif %}
                            <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-4">
                               <div class="contact__info pr-80">
                                  <h3 class="contact__title">Let's talk</h3>
      
                                  <div class="contact__details">
                                     <ul>
                                        <li>
                                           <h4>Our Location</h4>
                                           <p>{{site_manager.address}},<br> {{site_manager.location}}</p>
                                        </li>
                                        <li>
                                           <h4>Email Adress</h4>
                                           <p><a href="mailto:admin@thenursingace.com"><span class="__cf_email__" data-cfemail="52212722223d20263637213912353f333b3e7c313d3f">admin@thenursingace.com</span></a></p>                                       
                                        </li>
                                        <li>
                                           <h4>Hotline Number</h4>
                                           <p><a href="tel:+254763828734">+ (254) 763 828 734</a></p>
                                  
                                        </li>
                                     </ul>
                                  </div>
                               </div>
                            </div>
                            <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6">
                               <div class="contact__form">
                                
                               
                                  <form class="row g-3" action="" method="POST">
                                    {% csrf_token %}
                                    <div class="col-md-6">
                                       <label for="id_first_name" class="form-label">First name:</label>
                                      <input type="text" class="form-control" name="first_name" maxlength="100" required="" id="id_first_name">
                                    </div>
                                    <div class="col-md-6">
                                       <label for="id_last_name" class="form-label">Last name:</label>
                                      <input type="text" class="form-control" name="last_name" maxlength="100" required="" id="id_last_name">
                                    </div>
                                   
                                    <div class="col-md-12">                                   
                                      <label for="id_e_mail" class="form-label">Email:</label>
                                      <input type="email" class="form-control" name="e_mail" maxlength="100" required="" id="id_e_mail">
                                    </div>
                                   
                                    <div class="col-12">
                                       <label for="id_phone_number">Phone number:</label>
                                      <input type="text" class="form-control" name="phone_number" maxlength="13" id="id_phone_number">
                                    </div>
                                    <div class="col-12">
                                      <label for="id_business">Business:</label>
                                      <input type="text" name="business" class="form-control" maxlength="100" required="" id="id_business">
                                    </div>
                                    <div class="col-md-12">
                                       <label for="id_message"  class="form-label">Message:</label>
                                     
                                      <textarea name="message" cols="40" class="form-control" rows="10" required="" id="id_message" spellcheck="false"></textarea>
                                    </div>
                                  
                                    <div class="col-12">
                                      <button type="submit" class="w-btn w-btn-blue-5 w-btn-6 w-btn-14">Send Massage</button>
                                    </div>
                                  </form>
                              
                               </div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
             </div>
          </section>
          <!-- contact area end  -->
          {% include 'home/cta-section.html' %}
      </main>
      {% endblock %}

nursingace/nursingace/templates/home/cta-section.html
{% load static %}
         <section class="{{cta_infor.section_name }} cta__area blue-bg-10 pt-140 pb-130 p-relative fix z-index-1">

            <div class="cta__shape">
           
               <img class="cta-4-shape" src="{% static 'images/cta/cta-shape.png' %}" alt="">
               <img class="cta-4-shape" src="{{ cta_infor.get_image }}" alt="{{cta_infor.get_image_alt }}">  
     
            </div>
            <div class="container">
               <div class="row">
                  <div class="col-xxl-8 offset-xxl-2">
                     <div class="cta__content-4 text-center">
           
                        {% for block in timely_updates %}                       
                        <div class="section__title-wrapper section__title-wrapper-4 section__title-white text-center mb-45 wow fadeInUp" data-wow-delay=".3s">
                           <p class="eyebrow">{{block.value.eyebrow}}</p>
                           <h2 class="section__title section__title-4 wow fadeInUp" data-wow-delay=".3s">{{block.value.headline}}</h2>
                           <p class="wow fadeInUp" data-wow-delay=".5s">{{block.value.description}}</p>
                        </div>
                        {% endfor %}
                        <div class="subs-div">

                           <div class="cta__form mb-25 wow fadeInUp" data-wow-delay=".7s">
                              <form action="" id="subscribeForm">
                                 <input type="email" name="email" id="id_email" placeholder="Enter Your Email">
                                 <button type="submit">Subscribe</button>
                              </form>
                           </div>
                        </div>
                        <div class="cta__features">
                           <ul>
                              {% for block in self.timely_updates_bullet %}
                              <li>{{block}}</li>
                              {% endfor %}                             
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>